In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

Question: 

1. What two or three attributes to group together to make sense?
     Duration + 

2. 

In [15]:
test1 = [[1], [2], [8], [9], [10], [19]]
kmeans1 = KMeans(n_clusters = 3).fit(test1)
r = kmeans1.labels_
c = kmeans1.cluster_centers_
print(r)
print(c)


[0 0 1 1 1 2]
[[ 1.5]
 [ 9. ]
 [19. ]]


In [11]:
test2 = [[3, 8, 9], [4, 6, 5], [10, 9, 18], [1, 2, 2], [2, 3, 4] ,[19, 8 ,5]]
kmeans2 = KMeans(n_clusters = 4).fit(test1)
print(kmeans2.labels_)
kmeans2.n_iter_

[2 2 0 0 3 1]


1

In [4]:
sample_data = [[3, 8, 9], [4, 6, 5], [10, 9, 18], [1, 2, 2], [2, 3, 4] ,[19, 8 ,5],[4, 6, 10], [8, 9, 15],[7, 10, 30]
               ,[2, 9 ,16], [7, 2, 8], [8, 22, 7]]

In [7]:
# Methods for applying K means cluster onto the final data_array. 
# Input: data_array. K (cluster numer). 
# Output: Print out each cluster sand their centers.
def K_means(data_array, K):
    kmeans = KMeans(n_clusters = K).fit(data_array)
    labels = kmeans.labels_
    centers = kmeans.cluster_centers_
    clusters = [[] for i in range(K)] # Empty array to store the clusters.
    count = 0  # Count the index
    for ele in labels:
        clusters[ele].append(count)
        count += 1
    for i in range(K):
        print("Cluster", i ,":", clusters[i], " Centered at", centers[i])


In [28]:
K_means(test1, 3)

Cluster 0 : [0, 1]  Centered at [1.5]
Cluster 1 : [2, 3, 4]  Centered at [9.]
Cluster 2 : [5]  Centered at [19.]


In [29]:
K_means(test2, 4)

Cluster 0 : [0, 1]  Centered at [3.5 7.  7. ]
Cluster 1 : [5]  Centered at [19.  8.  5.]
Cluster 2 : [2]  Centered at [10.  9. 18.]
Cluster 3 : [3, 4]  Centered at [1.5 2.5 3. ]


In [10]:
K_means(sample_data, 4)

Cluster 0 : [2, 7, 8, 9]  Centered at [ 6.75  9.25 19.75]
Cluster 1 : [0, 1, 3, 4, 6, 10]  Centered at [3.5        4.5        6.33333333]
Cluster 2 : [11]  Centered at [ 8. 22.  7.]
Cluster 3 : [5]  Centered at [19.  8.  5.]


In [17]:
sample_2D = [[9, 2], [1, 8],  [1.4, 8.2], [4, 14], [2.5, 10.3], [11, 0.5], [2, 9], [10.2, 3]]

In [21]:
K_means(sample_2D, 3)

Cluster 0 : [1, 2, 4, 6]  Centered at [1.725 8.875]
Cluster 1 : [0, 5, 7]  Centered at [10.06666667  1.83333333]
Cluster 2 : [3]  Centered at [ 4. 14.]


In [20]:
# Method for computing the data_array from the list of dictionary.
def comupte_data_array(features_dictionary):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-20-732353d509dd>, line 3)